INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V1', 'Phoenix Market City', '5000', 'Whitefield', 'Bangalore');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V2', 'Mahalaxmi Race Course', '6000', 'Keshavrao Khadye Marg', 'Mumbai');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V3', 'Vagator Beach', '20000', 'Bardez', 'Goa');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V4', 'Boomrang BarXsocial', '35000', 'Koramangala', 'Bangalore');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V5', 'Bhartiya Mall', '10000', 'Thanisandra Main Road', 'Bangalore');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V6', 'Nexus Shantiniketan', '15000', 'Whitefield', 'Bangalore');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V7', 'Inner Circle Ground', '15000', 'Whitefield', 'Bangalore');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V8', 'R2 Grounds', '3000', 'Bandra East', 'Mumbai');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V9', 'T.M.C Ground', '18000', 'Hiranandani Estate,Thane West', 'Thane');
INSERT INTO venues (venue_id, venue_name, capacity, street_name, city) VALUES ('V10', 'SVP Stadium', '160000', 'Worli', 'Mumbai');